index.php
Modifique el archivo index.php para que cargue y muestre datos dinámicamente desde el archivo species.json. Ya se manejan errores como que no existan especies dentro del archivo json o que no exista el archivo species.json.
=> Modificaciones al archivo index.php

admin.php, admlogin.php, admlogout.php
Se agrego Auth al Dev anterior
=> Se agrego authy al sistema

admin.php
<h1>Cambios en el archivo **admin.php**</h1>
<h2>PHP</h2>
<ul>
<li>Corregido un error en el login, en donde se redirigia a adm-login(incorrecta), en vez de redirigir a admLogin(correcta)</li>
</ul>
<h2>HTML</h2>
<ul>
<li>Ahora El boton de submit por defecto se muestra como "Agregar Especie" y no "Confirmar Accion", ya que la opcion por defecto es Agregar</li>
<li>En el select de seleccion de especie ya no se puede dar click a "--Seleccione una especie--" y ahora este option esta desactivada por defecto al cargar la pagina.</li> 
</ul>
<h2>JavaScript</h2>
<h3>Se mejoró el formulario, para ofrecer una experiencia mas intuitiva para el administrador</h3>
<ul>
<li>Cada vez que se cambia a Agregar o Eliminar ahora se limpia el formulario</li> 
<li>Ahora --Seleccione una especie-- es la opcion …
=> Mejoras de intuitividad para el admin

mainpage.php, mainpagecss.css, mainpagejs.js
Cambios en HTML:
Estructura del HTML:
No hay cambios significativos en la estructura básica del HTML (como el uso de contenedores para secciones, navegación, etc.), pero el código CSS de fondo y funcionalidades adicionales, como el modo oscuro, podría implicar un ajuste en la organización de los elementos en el HTML, como agregar clases o identificadores que gestionen el modo oscuro.
Nuevo Botón de Modo Oscuro:
En el HTML, se debe haber añadido un nuevo botón (con un identificador como btn-darkmode) para permitir la alternancia entre el modo claro y el modo oscuro. Este botón interactúa con el CSS para cambiar el estilo de la página.
Navegación:
El HTML probablemente tiene un menú de navegación (menú hamburguesa) que es controlado por una clase dinámica (active), la cual activa o …
=> le mejore la accesibilidad y le añadi modo oscuro

PHP/CRUD.php, index.php
Se integro una API para la creación de qr.
Dicho QR se muestra directamente en las galerías puestas en índex.php.
Basándome en la creación del id único para generar la URL, use un array para almacenar la URL dentro de la QR generada por la API, ahora mismo la qr es escaneable, pero no dirige a ningún lado valido, no porque no este creada (ya verifique), sino pq simplemente el navegador no detecta dicha qr como existente dentro de la red.
=> Generacion de QR por medio de API

index.php
Se añadió funcionalidad al buscador mediante un script en el mismo archivo index.php, ahora es posible buscar a través de un id, nombre o nombre científico, el buscador funciona a medida que el usuario teclea y los resultados se van mostrando dinámicamente, además se muestra un mensaje cuando no se encuentren coincidencias con la búsqueda. Se hicieron cambios en cuanto al nombre de la pagina.
=> Cambios al archivo index.php

HTML/documentacion.html, HTML/index.html, HTML/programacion.html
inicie con una idea para el sobre nosotros, cree tres archivos, uno principal y otros dos que son para ingresar al presionar los botones del mencionado. Es html crudo, muy simple aun
=> Angela01Create the html for future abautUs

CSS/admin.css, CSS/index.css, PHP/CRUD.php, PHP/admin.php, index.php, species.json
Se agrego y perfecciono el modo oscuro de las paginas admin y index, como tambien se mejoro la funcionalidad de agregar especies, esta ahora detecta si anteriormente se había agregado un Animal y detecta las coincidencias de uno y el otro con tal de que no se muestre una segunda vez
=> Modo Oscuro (admin, index) y Mejoras en agregar especie (CRUD)

specie_info.css, specie_info.html
Le añadi un css, adaptandole a los colores que habia en la imagen
=> Le añadi un css al specie_info

CSS/admin.css, PHP/CRUD.php, PHP/admin.php, javaScript/admin.js
HTML:
-Agregado nuevo input en el formulario de admin.php: Recinto
PHP:
-Ajustado CRUD.php para registrar correctamente el nuevo input
JavaScript:
-Ajustado el codigo para que pueda obtener correctamente el nuevo input
=> Agregado nuevo input: Recinto

PHP/CRUD.php, PHP/admlogin.php
-Agregada carpeta reg
-Agregado archivo "AdminHistory.txt", el cual contiene todas las acciones realizadas por los administradores, junto con la fecha y hora de la realizacion. 
PHP:
-Agregadas varias contraseñas especificas para cada administrador
-Creadas variables de sesion para almacenar el nombre del administrador
-Agregada función para escribir en el archivo "AdminHistory", ahora se registra en el historial cada acción del CRUD
=> Cambios a acceso en admin y agregado registro de acciones

index.php
cada botón del animal lleva a una url
=> Se agrega correctamente una pestaña sobre cada animalindex.php

PHP/admin.php, PHP/admlogin.php, PHP/get_all_animals.php, javaScript/client_side_validation.js
JavaScript:
-Agregado archivo client_side_validation.js
-Creada una funcion para validar que no existan campos repetidos
-Agregados eventos para validar en tiempo real
-Creada una funcion para validar todos los campos
-Ahora el boton de envio solo se activa cuando se validan todos los campos correctamente 
PHP:
-Agregado archivo get_all_animals.php
-El archivo creado obtiene todos los valores del atributo solicitado y los muestra en formato JSON, para luego ser capturados desde javaScript
=> Validaciones del lado del cliente

PHP/CRUD.php, PHP/admin.php, javaScript/admin.js, javaScript/client_side_validation.js
!Atencion!! esta version es inestable, no funciona correctamente el CRUD y tampoco funciona el registro de acciones
-Las validaciones del lado del cliente fueron deshabilitadas(comentado todo el codigo relacionado) hasta encontrar solucion a los problemas encontrados que fueron mas complejos de lo esperado.
-Tambien se realizaron ajustes a CRUD para que place no sea un campo obligatorio
=> Fueron comentadas todas las validaciones del lado del cliente

PHP/CRUD.php, PHP/admin.php, javaScript/admin.js, specie_info.php
PHP
-Ahora los campos que pueden quedar vacios (scient_name, alt_name y place) se validan correctamente desde el lado del servidor.
-Correccion del nombre order a specie_order para evitar conflictos en consultas a la base de datos.
-Ajustado todo para que funcione correctamente con el cambio realizado al atributo order (ahora llamado specie_order)
-Ahora los campos vacíos se ajustaron para que se guarden como NULL en la base de datos.
-Ajustadas las comprobaciones de datos irrepetibles para que se comparen correctamente con los datos NULL en caso de estar vacios.
=> Cambio en validaciones del lado del servidor y mas

CSS/admin.css, PHP/CRUD.php, PHP/historyList.php, PHP/writeAdminHistory.php
HTML:
-Creada estructura completa de la pagina.
-Creado input de busqueda
PHP:
-Generacion de lista que contiene los datos leidos desde el archivo json AdminHistory.json
-Modificacion a la funcion writeFile para que guarde correctamente los datos en el json
CSS:
-Agregados estilos basicos para esta nueva pagina
JavaScript:
-Agregado color personalizado para cada administrador en la nueva pagina
-Agregado evento de busqueda por nombre del admin, especie, accion y id.
=> Agregada pagina de historial de administradores

CSS/admin.css, PHP/CRUD.php
CSS:
-Ahora se visualiza correctamente cuando un input esta validado o no en modo oscuro
-PHP:
-Ahora el tamaño de la imagen del QR generado es de 600x600 (antes 200x200)
=> Aumento del tamaño del QR y corrección de validaciones en modo oscuro

PHP/CRUD.php
PHP:
-Correcciones al eliminar la imagen qr
-Correcciones al mostrar el nombre de la especie al eliminar en el log
=> Ajustes minimos del CRUD al eliminar

indexClon.php
-La finalidad de este archivo es poder trabajar con el estilo de la pagina sin necesidad de la conexion a la base de datos
=> Agregado archivo indexClon

CSS/index.css, CSS/specie_info.css, indexClon.php, specie_infoClon.php
Cambios en:
- Specie_info: Ahora cuando el tamaño de la pantalla sea muy pequeña se agrega un padding para que el texto no este tan al borde. También el texto está justificado.
- Index.php: Ahora el logo a la izquierda, es un link y lleva al index.php. También el buscador se achica cuando la pantalla es muy pequeña. Por otra parte solucione el problema del menu, ahora el menu si se desplega, tiene un diseño mejor y esta siempre a la derecha. Por ultimo, agregue bajo la imagen  "ver detalles" con el icono para que sea mas intuitivo y se entienda que al hacer click, te llevara a otra pagina.
=> Cambios de ajustes de diseño
